import { useRef, useState, useEffect } from 'react';
import { useEditor, EditorContent } from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Image from '@tiptap/extension-image';
import { TableKit } from '@tiptap/extension-table';
import { TextB, TextItalic, ListBullets, ListNumbers, Quotes, ImageSquare, Table, ArrowCounterClockwise, ArrowClockwise, FloppyDisk, FilePdf, Sparkle } from '@phosphor-icons/react';
import { api, errorMessage, fileUrl } from './api';
import { AiFillDialog } from './AiFillDialog';
import { Alert } from './components';
import { sectionLabels, type DocumentData, type Section, type PdfJob, type ResearchInput, type Factor } from '../shared/contracts';
export function RichEditor({researchId,section,initial,onSaved,onDirty,readOnly,aiCurrent,factors,onAiApply}:{researchId:string;section:Section;initial?:DocumentData;onSaved:()=>Promise<void>;onDirty:(dirty:boolean)=>void;readOnly:boolean;aiCurrent:ResearchInput;factors:Factor[];onAiApply:(values:Partial<ResearchInput>)=>void}){
  const [aiHtml,setAiHtml]=useState<string|null>(null);
  const [revision,setRevision]=useState(initial?.revision||0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),[job,setJob]=useState<PdfJob|null>(null),[notice,setNotice]=useState('');
  const imageInput=useRef<HTMLInputElement>(null);const mounted=useRef(true);const refreshRef=useRef(onSaved);refreshRef.current=onSaved;
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
  async function insertImages(files:File[]){if(readOnly)return;setUploading(true);setError('');try{for(const file of files){const form=new FormData();form.append('editor_image',file);const result=await api<{id:string;url:string}[]>(`/files/research/${researchId}`,{method:'POST',body:form});editor?.chain().focus().setImage({src:result[0].url,alt:file.name}).run();}await refreshRef.current();}catch(e){setError(errorMessage(e));}finally{setUploading(false);}}
  const editor=useEditor({extensions:[StarterKit,Image.configure({allowBase64:false}),TableKit.configure({table:{resizable:false}})],content:initial?.html||'<p></p>',editable:!readOnly,shouldRerenderOnTransaction:true,
    editorProps:{attributes:{'aria-label':`${sectionLabels[section]}说明编辑器`,role:'textbox','aria-multiline':'true'},handlePaste:(_view,event)=>{const files=[...(event.clipboardData?.files||[])].filter(f=>f.type.startsWith('image/'));if(files.length){void insertImages(files);return true;}return false;},handleDrop:(_view,event)=>{const files=[...(event.dataTransfer?.files||[])];if(files.length){event.preventDefault();void insertImages(files);return true;}return false;},transformPastedHTML:html=>{const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('img').forEach(img=>{if(!/^\/api\/files\/[0-9a-f-]{36}\/content$/.test(img.getAttribute('src')||''))img.remove();});return doc.body.innerHTML;}},
    onUpdate:()=>{setDirty(true);onDirty(true);},
  });
  useEffect(()=>{if(!job||!['queued','running'].includes(job.status))return;const timer=setInterval(()=>{void api<PdfJob>(`/documents/jobs/${job.id}`).then(async next=>{if(!mounted.current)return;setJob(next);if(next.status==='completed'){setNotice('PDF 已生成，并已归入本研究的文件记录。');await refreshRef.current();}else if(next.status==='failed')setError(next.error_message||'转换失败');else if(next.status==='superseded')setNotice('文档已发生更新，请根据最新内容重新生成 PDF。');}).catch(e=>{setError(errorMessage(e));});},1500);return()=>clearInterval(timer);},[job?.id,job?.status]);
  async function save(){if(!editor)return;const saved=await api<DocumentData>(`/documents/research/${researchId}/${section}`,{method:'PUT',body:JSON.stringify({html:editor.getHTML(),revision})});setRevision(saved.revision);editor.commands.setContent(saved.html,{emitUpdate:false});setDirty(false);onDirty(false);await refreshRef.current();return saved;}
  async function act(pdf:boolean){setBusy(true);setError('');setNotice('');try{if(dirty||!revision)await save();if(pdf){setJob(await api<PdfJob>(`/documents/research/${researchId}/${section}/pdf`,{method:'POST',body:'{}'}));}else setNotice('编辑内容已保存，可随时继续修改。');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  if(!editor)return null;
  const pending=job&&['queued','running'].includes(job.status);
  const tools=[{label:'加粗',icon:TextB,active:editor.isActive('bold'),run:()=>editor.chain().focus().toggleBold().run()},{label:'斜体',icon:TextItalic,active:editor.isActive('italic'),run:()=>editor.chain().focus().toggleItalic().run()},{label:'无序列表',icon:ListBullets,active:editor.isActive('bulletList'),run:()=>editor.chain().focus().toggleBulletList().run()},{label:'有序列表',icon:ListNumbers,active:editor.isActive('orderedList'),run:()=>editor.chain().focus().toggleOrderedList().run()},{label:'引用',icon:Quotes,active:editor.isActive('blockquote'),run:()=>editor.chain().focus().toggleBlockquote().run()},{label:'插入图片',icon:ImageSquare,run:()=>imageInput.current?.click()},{label:'插入表格',icon:Table,run:()=>editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run()},{label:'撤销',icon:ArrowCounterClockwise,run:()=>editor.chain().focus().undo().run()},{label:'重做',icon:ArrowClockwise,run:()=>editor.chain().focus().redo().run()}];
  return <div className="document-editor"><Alert>{error}</Alert>{notice&&<div className="notice" role="status">{notice}</div>}<div className="editor-heading"><div><h3>{sectionLabels[section]}说明</h3><p>支持粘贴图文、插入图片与表格；图片也可直接拖入。</p></div><span className="status-label">{dirty?'有未保存的编辑':revision?`已保存 · 第 ${revision} 版`:'尚未编辑'}</span></div>
    {!readOnly&&<div className="editor-toolbar"><select aria-label="段落格式" value={editor.isActive('heading',{level:2})?'h2':editor.isActive('heading',{level:3})?'h3':'p'} onChange={e=>{if(e.target.value==='p')editor.chain().focus().setParagraph().run();else editor.chain().focus().toggleHeading({level:e.target.value==='h2'?2:3}).run();}}><option value="p">正文</option><option value="h2">二级标题</option><option value="h3">三级标题</option></select>{tools.map(t=><button key={t.label} type="button" title={t.label} aria-label={t.label} className={t.active?'active':''} onClick={t.run} disabled={busy||uploading}><t.icon size={19}/></button>)}{editor.isActive('table')&&<><button type="button" onClick={()=>editor.chain().focus().addRowAfter().run()}>加行</button><button type="button" onClick={()=>editor.chain().focus().addColumnAfter().run()}>加列</button><button type="button" onClick={()=>editor.chain().focus().deleteTable().run()}>删表</button></>}<input ref={imageInput} hidden type="file" accept="image/png,image/jpeg,image/webp" multiple onChange={e=>{void insertImages([...(e.target.files||[])]);e.target.value='';}}/></div>}
    <EditorContent editor={editor}/><div className="editor-footer"><span className="muted small">{uploading?'正在上传插图…':pending?'正在生成 PDF，请稍候…':'图文原稿与 PDF 分别保存，修改内容后请重新生成 PDF。'}</span><div className="actions">{initial?.pdf_file_id&&<a className="button ghost" href={fileUrl(initial.pdf_file_id)} target="_blank" rel="noreferrer">查看 PDF</a>}{!readOnly&&<><button type="button" className="secondary" disabled={busy||uploading} onClick={()=>setAiHtml(editor.getHTML())}><Sparkle size={17}/>AI 生成摘要</button><button className="secondary" disabled={busy||uploading||!!pending} onClick={()=>void act(false)}><FloppyDisk size={17}/>保存内容</button><button className="primary" disabled={busy||uploading||!!pending} onClick={()=>void act(true)}><FilePdf size={17}/>{pending?'转换中…':'保存并生成 PDF'}</button></>}</div></div>{aiHtml!==null&&<AiFillDialog researchId={researchId} current={aiCurrent} factors={factors} section={section} html={aiHtml} onClose={()=>setAiHtml(null)} onApply={values=>{onAiApply(values);setNotice('摘要已填入基本信息。请核对并保存研究资料；当前图文内容仍可继续编辑。');}}/>}</div>;
}
