import { lazy, Suspense, useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, UploadSimple, FloppyDisk, FileText, ClockCounterClockwise, ArrowSquareOut, Plus, Sparkle } from '@phosphor-icons/react';
import { api, errorMessage, fileUrl } from './api';
import { Alert, Field, FileLink, Loading, date, size } from './components';
import { AiFillDialog } from './AiFillDialog';
import { DatasetDescriptionDialog } from './DatasetDescription';
const RichEditor=lazy(()=>import('./Editor').then(module=>({default:module.RichEditor})));
import { researchTypes, sections, sectionLabels, roleLabels, type Research, type ResearchInput, type User, type Factor, type Section, type UploadEvent, type FileRecord } from '../shared/contracts';
const blank:ResearchInput={title:'',research_type:'要素集聚',factor_type_id:'',economic_data_names:[],mechanism_summary:'',impact_summary:'',risk_summary:'',policy_summary:''};
const materials=['image_pack','dataset','indicators','manuscript','mechanism_pdf','impact_pdf','risk_pdf','policy_pdf'] as const;
export function History({events}:{events:UploadEvent[]}){
  const actions:Record<string,string>={create:'创建成果',edit:'更新资料',upload:'上传材料',document:'保存文档',pdf:'生成 PDF'};
  return <div className="history-list">{!events.length&&<p className="muted">暂无操作记录</p>}{events.map(event=><div className="history-event" key={event.id}><span className="timeline-dot"/><div><div className="history-title"><strong>{event.uploader_name}</strong><span>{actions[event.action]||event.action}</span><time>{date(event.created_at)}</time></div><p>{event.research_title}</p>{event.files.map(f=><FileLink key={f.id} href={fileUrl(f.id)}>{f.name}</FileLink>)}<code className="record-id">记录 {event.id}</code></div></div>)}</div>;
}
export function ResearchDetail({initial,factors,user,onBack,onChanged}:{initial:Research|null;factors:Factor[];user:User;onBack:()=>void;onChanged:()=>void}){
  const [record,setRecord]=useState(initial),[form,setForm]=useState<ResearchInput>(initial||blank),[names,setNames]=useState(initial?.economic_data_names.join('\n')||'');
  const [tab,setTab]=useState<'basic'|'files'|'documents'|'history'>('basic'),[section,setSection]=useState<Section>('mechanism'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [dirty,setDirty]=useState(false),[docDirty,setDocDirty]=useState(false),[events,setEvents]=useState<UploadEvent[]>([]);
  const [descriptionOpen,setDescriptionOpen]=useState(false),[aiOpen,setAiOpen]=useState(false);
  const aiCurrent={...blank,...Object.fromEntries(Object.keys(blank).map(key=>[key,form[key as keyof ResearchInput]])),economic_data_names:names.split('\n').map(value=>value.trim()).filter(Boolean)};
  function applyAi(values:Partial<ResearchInput>){setForm(old=>({...old,...values}));if(values.economic_data_names)setNames(values.economic_data_names.join('\n'));setDirty(true);setNotice('智能建议已填入基本信息，核对后请点击“保存研究资料”。');}
  const editable=!record||record.owner_id===user.id||user.role==='admin';
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty||docDirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,docDirty]);
  async function refresh(){if(record){const next=await api<Research>(`/research/${record.id}`);setRecord(next);onChanged();}}
  function setField<K extends keyof ResearchInput>(key:K,value:ResearchInput[K]){setForm(f=>({...f,[key]:value}));setDirty(true);}
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');setNotice('');try{const data={...blank,...Object.fromEntries(Object.keys(blank).map(k=>[k,form[k as keyof ResearchInput]])),economic_data_names:names.split('\n').map(v=>v.trim()).filter(Boolean),...(record?{version:record.version}:{})};const next=await api<Research>(record?`/research/${record.id}`:'/research',{method:record?'PUT':'POST',body:JSON.stringify(data)});setRecord(next);setForm(next);setDirty(false);setNotice('研究资料已保存，可以继续上传材料或编辑说明文档。');onChanged();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  async function changeTab(next:typeof tab){if(docDirty&&!confirm('文档还有未保存的内容，确定离开编辑器吗？'))return;setDocDirty(false);setTab(next);setError('');if(next==='history'&&record){try{setEvents(await api<UploadEvent[]>(`/research/${record.id}/history`));}catch(e){setError(errorMessage(e));}}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!record)return;const el=e.currentTarget;setBusy(true);setError('');setNotice('');try{const data=new FormData(el);for(const [key,value] of [...data.entries()])if(value instanceof File&&!value.size)data.delete(key);await api(`/files/research/${record.id}`,{method:'POST',body:data});el.reset();await refresh();setNotice('材料已上传，文件映射与上传记录已同步更新。');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
  const current=(role:FileRecord['role'])=>record?.files?.find(f=>f.role===role&&f.is_current);
  return <div className="detail-page"><button className="back-link" onClick={()=>{if((dirty||docDirty)&&!confirm('还有未保存的内容，确定返回吗？'))return;onBack();}}><ArrowLeft size={17}/>返回研究资料</button><div className="page-heading"><div><span className="eyebrow">RESEARCH RECORD</span><h1>{record?record.title:'新建研究成果'}</h1><p>{record?`${record.owner_name} · ${record.factor_name} · 更新于 ${date(record.updated_at)}`:'先填写基本信息，再汇集数据、论文与分析说明。'}</p></div>{record&&<span className="badge">{record.research_type}</span>}</div>
    <Alert>{error}</Alert>{notice&&<div className="notice" role="status">{notice}</div>}
    <div className="tabs" aria-label="研究资料分区">{([['basic','基本信息'],['files','研究材料'],['documents','图文说明'],['history','上传记录']] as const).map(([key,label])=><button key={key} disabled={!record&&key!=='basic'} className={tab===key?'active':''} onClick={()=>void changeTab(key)}>{label}</button>)}</div>
    {tab==='basic'&&<form onSubmit={save} className="paper-panel"><div className="section-heading"><span className="section-number">01</span><div><h2>研究基本信息</h2><p>为成果建立清晰的分类与索引。</p></div>{editable&&<button type="button" className="secondary ai-entry" disabled={busy} onClick={()=>setAiOpen(true)}><Sparkle size={18}/>智能填充与摘要</button>}</div><fieldset disabled={!editable||busy}><Field label="研究题目 *"><input value={form.title} onChange={e=>setField('title',e.target.value)} required minLength={2} maxLength={250} placeholder="填写完整的研究题目"/></Field><div className="form-grid"><Field label="研究类型 *"><select value={form.research_type} onChange={e=>setField('research_type',e.target.value as ResearchInput['research_type'])}>{researchTypes.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="要素类型 *" hint={!factors.some(f=>f.active)?'管理员需要先在“要素与文件”中添加可选类型。':undefined}><select value={form.factor_type_id} onChange={e=>setField('factor_type_id',e.target.value)} required><option value="">请选择要素类型</option>{factors.filter(f=>f.active||f.id===form.factor_type_id).map(f=><option key={f.id} value={f.id}>{f.name}{f.active?'':'（已停用）'}</option>)}</select></Field></div><Field label="相关经济数据名称" hint="每行一个名称，例如：地区生产总值、就业人数。"><textarea rows={3} value={names} onChange={e=>{setNames(e.target.value);setDirty(true);}}/></Field>
      <div className="section-heading divided"><span className="section-number">02</span><div><h2>研究发现摘要</h2><p>供后续成果展示使用；详细论证可在“图文说明”中编辑。</p></div></div><div className="form-grid">{sections.map(s=><Field key={s} label={`${sectionLabels[s]}摘要`}><textarea rows={5} maxLength={5000} value={form[`${s}_summary`]} onChange={e=>setField(`${s}_summary`,e.target.value)} placeholder={`概述本研究的${sectionLabels[s]}…`}/></Field>)}</div></fieldset><div className="panel-footer"><span className="small muted">{record?'研究编号 '+record.id:'带 * 的项目为必填项。'}</span>{editable&&<button className="primary" disabled={busy}><FloppyDisk size={18}/>{busy?'正在保存…':'保存研究资料'}</button>}</div></form>}
    {tab==='files'&&record&&<form className="paper-panel" onSubmit={upload}>
      <div className="section-heading"><span className="section-number">01</span><div><h2>研究材料归档</h2><p>替换上传会保留历史文件；单个文件最多 25 MB，单次最多 100 MB。</p></div></div>
      <div className="material-grid">{materials.map(role=><div className="material-item" key={role}><div className="material-icon"><FileText size={24}/></div><div className="material-content">
        <div className="material-heading"><h3>{roleLabels[role]}</h3>{role==='indicators'&&<button type="button" className="dataset-add" aria-label={editable?'在线填写数据说明':'查看在线数据说明'} title={current('dataset')?'打开数据说明':'请先上传数据集'} disabled={busy||!current('dataset')} onClick={()=>setDescriptionOpen(true)}><Plus size={16}/><span>{editable?'在线填写':'在线说明'}</span></button>}</div>
        <p className="small muted">{role==='image_pack'?'ZIP / RAR 图片包，仅包含 PNG / JPG / WebP':role==='dataset'||role==='indicators'?'Excel 工作簿 · .xlsx':'PDF 文档 · .pdf'}</p>
        {current(role)?<><FileLink href={fileUrl(current(role)!.id)}>{current(role)!.original_name}</FileLink><span className="small muted">{size(current(role)!.size_bytes)}</span></>:<span className="missing">尚未上传</span>}
        {role==='dataset'&&current(role)?.dataset_summary&&<p className="dataset-status">预解析完成 · {current(role)!.dataset_summary!.field_count} 个字段 · {current(role)!.dataset_summary!.row_count.toLocaleString()} 行数据</p>}
        {role==='dataset'&&<p className="small muted">首行为完整表头，数据区内请勿留空行或合并单元格。</p>}
        {role==='indicators'&&<p className="small muted">{current('dataset')?.dataset_summary?.described?'当前数据集已保存在线说明，可点击加号查看或修改。':'也可点击加号在线填写；请先上传数据集。'}</p>}
        {editable&&<label className="upload-choice"><UploadSimple size={16}/><span>{current(role)?'替换文件':'选择文件'}</span><input aria-label={roleLabels[role]} type="file" name={role} accept={role==='image_pack'?'.zip,.rar':role==='dataset'||role==='indicators'?'.xlsx':'.pdf'} disabled={busy}/></label>}
      </div></div>)}</div>
      {editable&&<div className="panel-footer"><span className="muted small">数据集上传时会自动预检查；四类说明也可在网页中编辑。</span><button className="primary" disabled={busy}><UploadSimple size={18}/>{busy?'正在上传并检查…':'上传所选材料'}</button></div>}
    </form>}
    {tab==='documents'&&record&&<><div className="document-tabs">{sections.map(s=><button key={s} className={section===s?'active':''} onClick={()=>{if(docDirty&&!confirm('当前说明尚未保存，确定切换吗？'))return;setDocDirty(false);setSection(s);}}>{sectionLabels[s]}<span>{record.documents[s]?.pdf_file_id?(record.documents[s]?.pdf_revision===record.documents[s]?.revision?'PDF 已同步':record.documents[s]?.pdf_revision?'PDF 待更新':'已上传 PDF'):record.documents[s]?.revision?'已编辑':'待完善'}</span></button>)}</div><Suspense fallback={<Loading/>}><RichEditor key={`${record.id}-${section}`} researchId={record.id} section={section} initial={record.documents[section]} onSaved={refresh} onDirty={setDocDirty} readOnly={!editable} aiCurrent={aiCurrent} factors={factors} onAiApply={applyAi}/></Suspense></>}
    {tab==='history'&&<div className="paper-panel"><div className="section-heading"><ClockCounterClockwise size={26}/><div><h2>成果变更记录</h2><p>最近 200 次操作，包含上传时的姓名、题目和文件快照。</p></div></div><History events={events}/></div>}
    {record&&<div className="detail-footnote"><ArrowSquareOut size={14}/> 所有文件仅向已登录的课题组成员开放。</div>}
    {aiOpen&&<AiFillDialog researchId={record?.id} current={aiCurrent} factors={factors} onClose={()=>setAiOpen(false)} onApply={applyAi}/>}
    {descriptionOpen&&record&&<DatasetDescriptionDialog files={record.files.filter(file=>file.role==='dataset')} readOnly={!editable} onClose={()=>setDescriptionOpen(false)} onSaved={refresh}/>}
  </div>;
}
